version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin_panel:
    build: 
      context: .
      dockerfile: admin_panel/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - bot
      - db
    command: ["uvicorn", "admin_panel.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: sisu
      POSTGRES_USER: sisu_user
      POSTGRES_PASSWORD: sisu_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  default:
    name: sisu_net

volumes:
  postgres_data:
  redis_data: 