"""Create all tables

Revision ID: 3058c9b24eb1
Revises: 
Create Date: 2024-07-25 14:02:44.249419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3058c9b24eb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True, server_default='0'),
    sa.Column('rank', sa.String(), nullable=True, server_default='novice'),
    sa.Column('active_days', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('referrals', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('message_count', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('last_checkin', sa.DateTime(), nullable=True),
    sa.Column('is_supporter', sa.Boolean(), nullable=True, server_default='0'),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('pending_referral', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.String(), nullable=True, server_default='user'),
    sa.Column('supporter_tier', sa.String(), nullable=True, server_default='none'),
    sa.Column('supporter_until', sa.DateTime(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('video_count', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('is_banned', sa.Boolean(), nullable=True, server_default='0'),
    sa.Column('is_bot', sa.Boolean(), nullable=True, server_default='0'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_points'), 'users', ['points'], unique=False)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_user_id'), 'donations', ['user_id'], unique=False)
    
    op.create_table('channels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('link', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('bot_state',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(), unique=True, nullable=False),
        sa.Column('value', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('required_channels',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('channel_id', sa.String(), unique=True, nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('emoji_movies',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('emoji', sa.String(), nullable=False),
        sa.Column('answers', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('admin_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('target', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_dialogue_states',
        sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('history', sa.String(), server_default='[]', nullable=True),
        sa.Column('mood', sa.String(), server_default='neutral', nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id')
    )

    op.create_table('message_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('message_type', sa.String(), nullable=False),
        sa.Column('message_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('chat_points',
        sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('points', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_points')
    op.drop_table('message_logs')
    op.drop_table('user_dialogue_states')
    op.drop_table('admin_logs')
    op.drop_table('emoji_movies')
    op.drop_table('required_channels')
    op.drop_table('bot_state')
    op.drop_table('channels')
    op.drop_index(op.f('ix_donations_user_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_users_points'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 