"""Add ai_requests_hour field

Revision ID: 3d3f7ab510fb
Revises: add_performance_indexes
Create Date: 2025-07-03 21:53:20.618083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3f7ab510fb'
down_revision: Union[str, None] = 'add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_requests_hour', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_ai_requests_hour'), 'users', ['ai_requests_hour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ai_requests_hour'), table_name='users')
    op.drop_column('users', 'ai_requests_hour')
    # ### end Alembic commands ### 