name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy safety
      - name: Lint (black)
        run: black --check .
      - name: Lint (flake8)
        run: flake8 .
      - name: Type check (mypy)
        run: mypy . || true
      - name: Run tests
        run: pytest
      - name: Security audit (safety)
        run: safety check || true 